kind: Service
apiVersion: v1
metadata:
  name: webapp-{{ template "cowbull.fullname" . }}-svc
  labels:
    run: webapp
    app: webapp
    tier: webappFrontend
spec:
  selector:
    app: webapp-{{ template "cowbull.fullname" . }}
    tier: webappFrontend
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
  type: LoadBalancer