apiVersion: v1
kind: Service
metadata:
  name: redis-{{ template "cowbull.fullname" . }}-svc
#  name: redis
spec:
  ports:
  - port: 6379
    name: peer
  clusterIP: None
  selector:
    app: redis-{{ template "cowbull.fullname" . }}