apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-{{ template "cowbull.fullname" . }}
spec:
  replicas: {{ .Values.dbServer.replicas }}
  serviceName: redis-{{ template "cowbull.fullname" . }}-svc
  template:
    metadata:
      labels:
        app: redis-{{ template "cowbull.fullname" . }}
    spec:
      containers:
      - command: [bash, -c, . /redis-config/init.sh]
        image: {{ printf "%s:%s" .Values.dbServer.image .Values.dbServer.imagetag }}
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - mountPath: /redis-config
          name: config
        - mountPath: /redis-data
          name: data
      - command: [bash, -c, . /redis-config/sentinel.sh]
        image: {{ printf "%s:%s" .Values.dbServer.image .Values.dbServer.imagetag }}
        name: sentinel
        volumeMounts:
        - mountPath: /redis-config
          name: config
      volumes:
      - configMap:
          defaultMode: 420
          name: redis-config-{{ template "cowbull.fullname" . }}
        name: config
      - emptyDir:
        name: data